exclude_paths:
  - vendor
keep:
  ## public api
  - PathList

  # query
  - include?
  - member?
  - each
  - ===
  - to_proc

  # build
  - ignore
  - ignore!
  - only
  - only!
  - and
  - and!
  - any
  - any!
  - append
  - append!
  - gitignore
  - gitignore!
