exclude_paths:
  - vendor
  - bin/benchmark
keep:
  ## public api
  - PathList

  # query
  - include?
  - member?
  - each
  - ===
  - to_proc

  # build
  - ignore
  - ignore!
  - only
  - only!
  - union!
  - union
  - intersection!
  - intersection
  - '&'
  - '|'
  - gitignore
  - gitignore!
