exclude_paths:
  - vendor
keep:
  ## public api
  - PathList

  # query
  - include?
  - member?
  - each
  - ===
  - to_proc

  # build
  - ignore
  - ignore!
  - only
  - only!
  - all
  - all!
  - any
  - any!
  - gitignore
  - gitignore!
