name: CI

on: [push, pull_request]

jobs:
  rspec:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, '3.0', 3.1, 3.2, ruby-head, jruby-9.4, jruby-head]
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: gem install syntax_suggest; bundle exec rspec

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - run: gem install syntax_suggest; COVERAGE=1 bundle exec rspec

      - uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: 'coverage/*'
          retention-days: 1
        if: ${{ failure() }}

  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - run: gem install syntax_suggest; bundle exec rubocop

  spellr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true
    - run: gem install syntax_suggest; bundle exec spellr

  leftovers:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true
    - run: gem install syntax_suggest; bundle exec leftovers

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true
    - run: gem install syntax_suggest; bundle exec rake build
